### ISSUE TITLE
Error: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Grulfen** [JustasB/SwarmSight#3]
I got this error message when running SwarmSight. The error occurs after a few minutes of footage.

In the Activity graph area there appears an error message from time to time while running which disappears quickly. I'm attaching a screenshot of that error message
![Oxyplot exception](https://cloud.githubusercontent.com/assets/690778/19533006/4ce20c3a-963e-11e6-9db3-8c7991201992.png)

The error messages seem to indicate that a collection that is being iterated over is changing or something similar.

**Comment by JustasB** [comment]
@Grulfen Thanks for reporting this. I will open a separate issue for the oxyplot message. Will let you know when either of these have been fixed.

**Comment by JustasB** [comment]
@Grulfen This problem should be fixed. Please follow the steps to get the latest version:

https://github.com/JustasB/SwarmSight/blob/master/README.md#download--install

If you still get the error, please re-open this issue, and, if possible, share the video file that reproduces the problem.
