### ISSUE TITLE
Movement capture: position data

### ISSUE THREAD

**Issue by pivdnber** [JustasB/SwarmSight#7]
Hi, I was wondering if one of Swarmsight 's modules can also provide the movement output (position) instead of the activity level through automatic tracking?

**Comment by JustasB** [comment]
Hi @pivdnber,

The [Motion Analysis](http://swarmsight.org/MotionAnalysis.html) module currently only provides aggregate activity level only. Positions of individual moving objects are not tracked - there are some plans to implement tracking, but nothing concrete yet. The [Antenna Tracking module](http://swarmsight.org/AppendageTracking.html) will track the tips of an insect antennae.

What objects are you trying to track? Insects, rodents? Do you have a sample video or a few screenshots?
