### ISSUE TITLE
Stand-alone version

### ISSUE THREAD

**Issue by RussellButson** [JustasB/SwarmSight#9]
Do you have a setup file for installing on a non-networked computer? The current setup file requires access to the internet for verification.

Regards,

Russell

**Comment by JustasB** [comment]
Hi Russell,

I was able to install it without an internet connection by following these steps:

- Download the repository zip file: https://github.com/JustasB/SwarmSight/archive/master.zip
- Extract the zip and go into the Setup folder within, then pick the module folder e.g. AntennaTracking
- Then run the setup.exe file. It should install from the local copy without internet access.

You can also run the application without installing, by going into the module folder, then Application Files/SwarmSight.... and running the application .exe file directly.

One issue you may run into with the offline method is missing dependencies that get automatically installed with the online installer. You may need to install .Net Framework 4.5 first (if your OS doesn't have it already): https://www.microsoft.com/en-us/download/details.aspx?id=42642

Let me know if this helps.

Best regards,

Justas

**Comment by RussellButson** [comment]
Hi Justas,

We have had success with the installation, but now find we are able to run our video clips.

Is there a file limit?  Our footage is in the range of 1-2 GB.

Any guidance on this greatly appreciated.

Russell








Hi Russell,

I was able to install it without an internet connection by following these steps:

  *   Download the repository zip file: https://github.com/JustasB/SwarmSight/archive/master.zip
  *   Extract the zip and go into the Setup folder within, then pick the module folder e.g. AntennaTracking
  *   Then run the setup.exe file. It should install from the local copy without internet access.

You can also run the application without installing, by going into the module folder, then Application Files/SwarmSight.... and running the application .exe file directly.

One issue you may run into with the offline method is missing dependencies that get automatically installed with the online installer. You may need to install .Net Framework 4.5 first (if your OS doesn't have it already): https://www.microsoft.com/en-us/download/details.aspx?id=42642

Let me know if this helps.

Best regards,

Justas

**Comment by JustasB** [comment]
Hi Russell, is there a message or an error that you encounter when you try to use the files?

**Comment by RussellButson** [comment]
Hi Justas,

I have reload but still same issue – copy of error message attached.

Russell

**Comment by JustasB** [comment]
Hi Russel, I don't see the attachment here. Can you attach it to the github issue (https://github.com/JustasB/SwarmSight/issues/9) or email it directly to me (justas AT asu.edu)?

**Comment by RussellButson** [comment]
Hi Justas,

I believe we found the issue occurred as a result of us using MKV file format.

We are currently converting our files to MP4. However, while swarmsight is now working correctly, it takes many hours to process with the software often freezing at completion.

We are operating with large files – 1 GB (4-9 hours of recording)

We are on a tight timeline – any help would be greatly appreciated – love the software, it produces exactly what we want.

Regards,

Russell


-----------------------------------
Russell Butson
Senior Lecturer in Higher Education
Higher Education Development Centre
65-75 Union Place West
University of Otago
P O Box 56
Dunedin
New Zealand

Ph   64 3 479 5789    Fax  64 3 479 8362
E: russell.butson@otago.ac.nz<mailto:russell.butson@otago.ac.nz>
W: http://hedc.otago.ac.nz/
[cid:image001.jpg@01D3A740.ED205120]

**Comment by JustasB** [comment]
Hi Russell,

I would recommend splitting the large files into smaller ones first to see if you're getting the results you want. Then increase the file sizes gradually and check for any issues related to file size.

The software can process the files at 30-60 frames per second depending on your hardware, so a 9 hr video would take about 4.5-9 hours to process. Furthermore, a 9 hr video recorded at 30 FPS would have ~1 million frames, and so the resulting CSV file would have ~1 million rows. The freezing might be happening if the computer's RAM is used up during the processing or if the disk to which the CSV files are saved runs out of space. Of course, it could also be some bug in the software.

I use [ffmpeg ](https://ffmpeg.org/) software to split large files and convert files between video formats.

If possible, can you upload one of the problematic files to Google Drive or Dropbox and share it with me? With the file in hand, I could diagnose the problem better.

If you find that smaller files still result in crashes/freezing/errors please let me know, and share the file if possible.

Best regards,

Justas

**Comment by RussellButson** [comment]
Hi Justas,

I have meetings all morning, but could upload a file later today – in say 5 hours.

Splitting is possible… but takes more time.

PROCESS…

·         Convert to mp4 = 1:30 hour 30fps per file/clip

·         File splitting - ??

·         Swarmsight  threshold-35 | motion contrast x1 | speed high with  accuracy at 25% | storage to external HD – 9TB (80% free space) – 6 hours

·         = 8-9 hours
I have 60 video clips to process ☺


I have tested on three different configuration including SSD – but same issue fast for the first 40% then progressively slower. The main computer specs: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz so computation power shouldn’t be an issue.

I am pretty sure the problem is caused by the file size.

Were we correct that swarmsight doesn’t recognise mkv files?

Russell

**Comment by RussellButson** [comment]
Hi Justas,

Here is the error message we received when using mkv files.

R




From: Russell Butson
Sent: Monday, 23 July 2018 4:51 AM
To: 'JustasB/SwarmSight' <reply@reply.github.com>
Subject: RE: [JustasB/SwarmSight] Stand-alone version (#9)

Hi Justas,

I have reload but still same issue – copy of error message attached.

Russell

**Comment by RussellButson** [comment]
I've shared an item with you:

Dp-3 10-20.m4v
https://drive.google.com/file/d/1fsAdhhNBMiGs-1KvJnJYZxeQBq8AL3zJ/view?usp=sharing&ts=5b5cdabc

It's not an attachment – it's stored online. To open this item, just click  
the link above.

**Comment by RussellButson** [comment]
Hi Justas,

Re: splitting - I would have to split the files into 8-10 sections – very time consuming + I would then need to merge all of the csv files – again very time consuming.

I can’t seem to see a pattern in the slowing down behaviour. Therefore, I am not really sure what is happening.

I have upload a portion of a file for you to test to a google drive – you should have received a url link.

As you can see on the attached image – SS slows down in the final 3rd – no errors + still processing – cpu/memory – but very very slow. This image is of a SS process that has been running for 12 hours. The first 1 hour was processed in less than 10mins.

Any help ready appreciated – desperate to get access to these frequencies graphs for our study – they are absolutely perfect! for our analysis.

Hope you can help.

Russell

**Comment by JustasB** [comment]
Hi Russel, I've received the video file and will be looking into the issue you described. Will let you know what I find, Justas

**Comment by RussellButson** [comment]
Excellent. I really appreciate you help on this.

Russell

**Comment by JustasB** [comment]
Hi Russel, 

I was able to reproduce the slow-down issue and was able to find a solution. The problem was the combination of a long video and updating the activity plot. Once there are enough points, the plot library would spend more and more time updating the activity plot and thus you would see the slowdown after a while.

As a fix, I added a checkbox "Update Plot" to control the plot updating. Before starting the analysis, clear the checkbox and this will not add new points to the activity plot and the frame rate should not slow down. It will still record the changes and you should see them in the Changed Pixels label.

![image](https://user-images.githubusercontent.com/10732358/43432391-7a18aaa4-9427-11e8-8db6-bc6fae552ca6.png)

Furthermore, I added an option to chose the file name to the Save functionality. Now, clicking "Save.." will open a dialog to select a file destination.

Finally, I've updated the video decoder library to the latest version. I don't know for sure, but you should try running one of the ealier MKV files to see if the updated version is able to open it. If not, the MP4 method should still work.

You can follow the steps I described earlier to download the updated version: https://github.com/JustasB/SwarmSight/issues/9#issuecomment-392116399

Let me how it goes,

Justas

**Comment by RussellButson** [comment]
This is perfect timing – I will try now.

Thank you so much for doing this.

Russell

**Comment by RussellButson** [comment]
No luck with the mkv – same error message as before, but worked fine with m4v

Thank you so much!  Off to analyse 50 hours of video.

R

**Comment by JustasB** [comment]
Glad to hear it's working. 

For the MKV issue, I've been able to open a few MKV files with the software without errors. It makes me think that there is something specific about the files you have and the way the software reads them. 

If possible, can you upload a small MKV clip that produces the error?

**Comment by RussellButson** [comment]
Hi Juatas,

I have upload a MKV file to the same folder as before

R

**Comment by JustasB** [comment]
Hi Russel, 

The link I have:

https://drive.google.com/file/d/1fsAdhhNBMiGs-1KvJnJYZxeQBq8AL3zJ/view?usp=sharing&ts=5b5cdabc

shows the m4p file. But, I don't see any other files. 

Can you resend a link to the folder?

**Comment by RussellButson** [comment]
Upload failed…. Try now.

R

**Comment by JustasB** [comment]
When I click on the link

https://drive.google.com/file/d/1fsAdhhNBMiGs-1KvJnJYZxeQBq8AL3zJ/view?usp=sharing&ts=5b5cdabc

this is what I see:

![image](https://user-images.githubusercontent.com/10732358/43556055-a4b7c07e-95b2-11e8-88c7-a1eb31e665f3.png)
